# Create a local config.yml file from this template

local:
  app:
    local_to_remote_ports:
      "80": "80"
  platform:
    local_to_remote_ports:
      "8080": "8080"

remote:
  rabbitmq:
    local_to_remote_ports:
      "5672": "5672"
      "15672": "15672"
  grafana:
    local_to_remote_ports:
      "3000": "3000"
  alloy:
    local_to_remote_ports:
      "4317": "4317"
      "4318": "4318"

ssh:
  user:
  host:
  port:
  identity_file:

docker:
  network:
    name: common
    external: false
