services:
  bifrost:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - company
    volumes:
      - ${SSH_KEY_PATH}:/root/ec2.pem:ro
      - ./bifrost.sh:/usr/local/bin/bifrost.sh:ro
      - ./config.yml:/root/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["/bin/sh", "/usr/local/bin/bifrost.sh", "/root/config.yml", "/root/ec2.pem"]
    env_file:
      - .env
